package bot.schedulebot.enums;

public enum InstanceAdditionStage {
    SUBJECT_START,
    SUBJECT_NAME,
    GROUP_START,
    GROUP_NAME,
    TASK_START, TASK_NAME, TASK_SUBJECT, TASK_DESCRIPTION, TASK_DEADLINE,
    GROUP_JOIN,
    APPOINTMENT_START, APPOINTMENT_DATE,
    TASK_IMAGE,
    TASK_NAME_NO_IMAGE, TASK_FILE, TASK_IMAGE_NO_FILE, ANNOUNCEMENT_FILE, ANNOUNCEMENT_IMAGE, ANNOUNCEMENT_IMAGE_SKIP_FILE, ANNOUNCEMENT_TITLE, ANNOUNCEMENT_TITLE_SKIP_IMAGE, ANNOUNCEMENT_TEXT,
    ANNOUNCEMENT_START, NOTIFICATION_START, NOTIFICATION_TEXT, NOTIFICATION_DATE, NOTIFICATION_TIME, NOTIFICATION_FREQUENCY, NONE
}
