package bot.schedulebot.enums;

public enum TodayTasksInfoMode {
    MAIN,
    APPOINTMENTS_FOR_TODAY,
    APPOINTMENTS_WITH_DEADLINE_TODAY,
    OUTDATED_TASKS, OUTDATED_APPOINTMENTS, OUTDATED_UNAPPOINTED_TASKS, UNAPPOINTED_TASKS_WITH_DEADLINE_TODAY
}
